config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
    
  resources :users, only: [:index, :new, :create] do
    collection do
      get 'step1'   #予約日時登録
      post 'step2'   #名前（漢字・カナ）・生年月日・電話番号・メールアドレス登録
      post 'confirm' #確認画面、確定ボタンでcreateが走る
      
    # 変更点
      # get :step1
      # post :step2
      # post :confirm
    # 変更点
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.new
  end


  # def new
  #   @user = User.new
  # end

  # def next
  #   @user = User.new(user_params)
  #   # render :new if @user.invalid?
  # end
  
  def step1
    @user = User.new
    # @tmp  = "aaa"
  end
    
  def step2
    session[:book_date] = user_params[:book_date]
    @user = User.new
    
    # 変更
    # @user = User.new(user_params)
    # render :step1 if @user.invalid?
  end
  
  def confirm
    session[:name_first_kanji]  = user_params[:name_first_kanji]
    session[:name_last_kanji]   = user_params[:name_last_kanji]
    session[:name_first_kana]   = user_params[:name_first_kana]
    session[:name_last_kana]    = user_params[:name_last_kana]
    session[:birthday]          = user_params[:birthday]
    # session[:birthday]          = user_params["birthday(2i)"]
    # session[:birthday]          = user_params["birthday(3i)"]
    session[:phonenumber]       = user_params[:phonenumber]
    session[:mailaddress]       = user_params[:mailaddress]
    @user   = User.new
    
    
    @book_date        = session[:book_date]
    @name_first_kanji = session[:name_first_kanji]
    @name_last_kanji  = session[:name_last_kanji]
    @name_first_kana  = session[:name_first_kana]
    @name_last_kana   = session[:name_last_kana]
    @birthday         = session[:birthday]
    @phonenumber      = session[:phonenumber]
    @mailaddress      = session[:mailaddress]
    
    # @users  = User.all
    # binding.pry
    
    # 変更
    # @user = User.new(user_params)
    # render :new and return if params[:back]
    # render :next if @user.invalid?(:confirm)
    # render :step1 and return if params[:back]
    # render :step2 if @user.invalid?(:confirm)
  end
  
    
  # def create
  #   @user = User.new(user_params)
  #   @user.save
  #   render :next and return if params[:back]
  #   render :confirm and return if !@user.save
  #   redirect_to @user
  # end


  def create
    User.create(
      book_date:        session[:book_date],
      name_first_kanji: session[:name_first_kanji],
      name_last_kanji:  session[:name_last_kanji],
      name_first_kana:  session[:name_first_kana],
      name_last_kana:   session[:name_last_kana],
      birthday:         session[:birthday],
      phonenumber:      session[:phonenumber],
      mailaddress:      session[:mailaddress]
    )
    
    # 変更
    # render :step2 and return if params[:back]
    # render :confirm and return if !@user.save
    # redirect_to @user
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(
    # params.permit(
      :book_date, 
      :name_first_kanji, 
      :name_last_kanji, 
      :name_first_kana, 
      :name_last_kana, 
      :birthday, 
      :phonenumber, 
      :mailaddress
    )
  end
  
  
  # def birthday_join
  #   # パラメータ取得
  #   date = params[:user][:birthday]

  #   # 年月日別々できたものを結合して新しいDate型変数を作って返す
  #   Date.new date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i

  # end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaiyojiHp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>大陽寺予約フォーム</title>
</head>

<body>
  <header>
    <a class="a-top" href="/users">
      <h1>大陽寺</h1>
    </a>
    <h2>ご予約フォーム</h2>
    <div class="step_flow">
      <ul>
        <li class="li-step1">
          <div>STEP1</div>
          <div>日時を選ぶ</div>
        </li>
        <li class="li-step2">
          <div>STEP2</div>
          <div>お客様情報の入力</div>
        </li>
        <li class="li-step3">
          <div>STEP3</div>
          <div>ご予約内容の確認</div>
        </li>
      </ul>
    </div>
  </header>
 </body>
 

app/views/users/confirm.html.erb
<%= render partial: "user", user: @user %>

<%= form_for @user, url: users_path, method: :post do |f| %>

  <main>
    <section class="form-box">
      <h3>
        <span class="num">
          <span class="num_st">STEP</span>
          <span class="num_nm">3</span>
        </span>
        ご予約内容の確認
      </h3>
      
      <%#
      <% @users.each do |user| %>
      
      <div class="confirm-book">
        <div class="book-info">ご予約情報</div>
          <div class="confirm-book-block">
            <div class="book_date">
              <label class="book_date-label">ご予約日
              <div class="book_date-info">
                
              <%= @book_date %>
              
              <%#
              <% binding.pry %>
              
              </div>
              
            </div>
            <div class="book-time">
              <label class="book-time-label">ご予約時間
              <div class="book-time-info">
                
              </div>
            </div>
          </div>
        <div class="step-back-button">
          <%#=
          <%= f.submit "←日時を変更する", name: :back, :class => "step-back"%>
          <button class="step-back">←日時を変更する</button>
        </div>
      </div>
        
      <div class="user-book-info">
        <div class="user-info">お客様情報</div>
          <div class="user-info-book-block">
            <div class="user-name">
              <label class="user-name-label">お名前（漢字）</label>
              <div class="user-name-kanji-info">
                <%= @name_first_kanji %>
                <%= @name_last_kanji %>
              </div>
            </div>
            <div class="user-name-kana">
              <label class="user-name-kana-label">お名前（カナ）</label>
              <div class="user-name-kana-info">
                <%= @name_first_kana %>
                <%= @name_last_kana %>
              </div>
            </div>
            <div class="user-birthday">
              <label class="user-birthday-label">生年月日</label>
              <div class="user-birhday-info">
                <%= @birthday %>
              </div>
            </div>
            <div class="user-phonenumber">
              <label class="user-phonenumber-label">電話番号</label>
              <div class="user-phonenumber-info">
                <%= @phonenumber %>
              </div>
            </div>
            <div class="user-mailaddress">
              <label class="user-mailaddress-label">メールアドレス</label>
              <div class="user-mailaddress-info">
                <%= @mailaddress %>
              </div>
            </div>
          </div>
            <div class="step-back-button">
              <%#=
              <%= f.submit "←お客様情報を変更する", name: :back, :class => "step-back" %>
              <button class="step-back">←お客様情報を変更する</button>
            </div>
        </div>
        
        <%#
        <% end %>
        
      </div>
        
    </section>
  </main>
  <section class="form-info">
    <%= f.submit '予約を確定', :class => 'confirm-button'%>
  </section>

<% end %>

app/views/users/create.html.erb
<a href="/users">予約を確定しました</a>

app/views/users/index.html.erb
<div data-turbolinks="false">
 <%= link_to "予約フォーム", step1_users_path %>
</div>

<!--<a href="/users/step1">予約フォーム</a>-->

app/views/users/step1.html.erb
<%= render partial: "user" %>



<%= form_for @user, url: step2_users_path, method: :post do |f| %>
<main>
<section class="form-box">
  <h3>
    <span class="num">
      <span class="num_st">STEP</span>
      <span class="num_nm">1</span>
    </span>
    日時を選択
    <%= @tmp %>
  </h3>
  
  <div class="user-input-book_date">  
    <label>ご希望の日時</label>
    <span class="required">必須</span>
    <section class="form-box">
      <div class="book_date-select">
        <%= f.date_field :book_date %>
      </div>
    </section>
  </div>
</section>
</main>

<section class="form-info">
  <%= f.submit '次へ', :class => 'next-button'%>
</section>
<% end %>

app/views/users/step2.html.erb
<%= render partial: "user" %>
  
  <%= form_for @user, url: confirm_users_path, method: :post do |f| %>
  
    <main>
      <section class="form-box">
        <h3>
          <span class="num">
            <span class="num_st">STEP</span>
            <span class="num_nm">2</span>
          </span>
          お客様情報の入力
        </h3>
        
        <div class="user-input-name-kanji">  
          <label>お名前（漢字）</label>
          <span class="required">必須</span>
            <div class="input">
              <div class="name">
                <%= f.text_field :name_first_kanji, :placeholder => "姓" %>
              </div>
              <div class="name">
                <%= f.text_field :name_last_kanji, :placeholder => "名" %>
            </div>
            </div>
        </div>
        
        <div class="user-input-name-kana">  
          <label>お名前（カナ）</label>
          <span class="required">必須</span>
            <div class="input">
              <div class="name">
                <%= f.text_field :name_first_kana, :placeholder => "セイ" %>
              </div>
              <div class="name">
                <%= f.text_field :name_last_kana, :placeholder => "メイ" %>
              </div>
            </div>
        </div>
        </div>
        
        <div class="user-input-birthday">  
          <label>生年月日</label>
          <span class="required">必須</span>
          <div class="input">
            <%= f.date_select :birthday, 
            use_month_numbers: true, start_year: 1930,
            end_year: (Time.now.year - 18),
            default: Date.new(Time.now.year - 18, 1, 1),
            with_css_classes: "input"
            %>
          </div>
        </div>
        
        <div class="user-input-phonenumber">  
          <label>お電話番号（半角）</label>
          <span class="required">必須</span>
            <div class="input">
            <%= f.text_field :phonenumber, :placeholder => "お電話番号（半角）"%>
            </div>
        </div>
        
        <div class="user-input-mailaddress">  
          <label>メールアドレス（半角）</label>
          <span class="required">必須</span>
            <div class="input">
              <%= f.email_field :mailaddress, :placeholder => "メールアドレス（半角）"%>
            </div>
        </div>
        
        <div class="privacypolicy">  
          <label>プライバシーポリシー</label>
          <span class="required">必須</span>
            <p class="policy"> プライバシーポリシー</p>
        </div>
        
        <div class="container">
          <div class="form-agree">
            <div class=" agree-position custom-checkbox checkbox-text">
              <input type="checkbox" class="custom-control-input" id="custom-check-1" style="transform:scale(2);">
              <label class="agree-text custom-control-label" for="custom-check-1">上記に同意する</label>
            </div>
          </div>
        </div>
      </section>
    </main>
    
    <section class="form-info">
      <%= f.submit '確認する', :class => 'valification-button'%>
    </section>
  <% end %>